# Generated by Django 4.0.3 on 2022-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='characters',
            field=models.ManyToManyField(to='main_app.character'),
        ),
    ]
